# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in lambdatest-selenium-driver.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rubocop", "~> 1.21"

gem 'lambdatest-sdk-utils', "~> 1.0"